import { StyleSheet } from 'react-native';
import { COLORS } from '@/src/styles/styles';

export const onboardingStyles = StyleSheet.create({
  safeArea: {
    backgroundColor: COLORS.background,
  },
  scroll: {
    flexGrow: 1,
    paddingBottom: 120,
  },

  // Header
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: COLORS.white,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  logoBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#6C63FF',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  logoBadgeText: {
    color: COLORS.white,
    fontWeight: '700',
    fontSize: 12,
  },
  logoText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  stepIndicator: {
    fontSize: 13,
    color: COLORS.textMedium,
    fontWeight: '500',
  },

  // Progress steps row
  stepsRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  stepItem: {
    alignItems: 'center',
    width: 64,
  },
  stepCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: COLORS.grayBg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stepCircleActive: {
    backgroundColor: COLORS.primary,
  },
  stepCircleDone: {
    backgroundColor: COLORS.primary,
  },
  stepCircleText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textLight,
  },
  stepCircleTextActive: {
    color: COLORS.white,
  },
  stepLabel: {
    fontSize: 11,
    color: COLORS.textLight,
    marginTop: 6,
    textAlign: 'center',
  },
  stepLabelActive: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  stepConnector: {
    flex: 1,
    height: 2,
    backgroundColor: COLORS.border,
    marginTop: 17,
    marginHorizontal: 2,
  },
  stepConnectorActive: {
    backgroundColor: COLORS.primary,
  },

  // Body
  body: {
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  title: {
    fontSize: 22,
    fontWeight: '700',
    color: COLORS.textDark,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textMedium,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 20,
  },

  // Goal form
  inputGroup: {
    marginBottom: 20,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
    marginBottom: 10,
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    height: 52,
  },
  dropdownText: {
    flex: 1,
    fontSize: 14,
    color: COLORS.textDark,
  },
  dropdownInput: {
  flex: 1,
  fontSize: 14,
  color: COLORS.textDark,
  padding: 0,
  margin: 0,
  height: '100%',
  textAlignVertical: 'center',
  includeFontPadding: false,
  },
  dropdownPlaceholder: {
    color: COLORS.textLight,
  },
  optionsList: {
    marginTop: 6,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    maxHeight: 220,
    overflow: 'hidden',
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  optionText: {
    fontSize: 14,
    color: COLORS.textDark,
  },
  assignedTag: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },
  optionEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  optionEmptyText: {
    fontSize: 14,
    color: COLORS.textLight,
    textAlign: 'center',
  },

  // Year selector
  yearRow: {
    flexDirection: 'row',
    gap: 12,
  },
  yearPill: {
    flex: 1,
    paddingVertical: 16,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
    alignItems: 'center',
  },
  yearPillSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  yearPillText: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  yearPillTextSelected: {
    color: COLORS.white,
  },

  // Action buttons (bottom)
  actionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  backBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textDark,
    marginLeft: 6,
  },
  primaryBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
    paddingVertical: 16,
    borderRadius: 12,
  },
  primaryBtnDisabled: {
    opacity: 0.5,
  },
  primaryBtnText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '700',
    marginRight: 6,
  },
  hintBelowBtn: {
    marginTop: 10,
    fontSize: 12,
    color: COLORS.primary,
    textAlign: 'center',
  },

  // ============== Self-Assessment ==============
  sectionLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textDark,
    marginBottom: 12,
  },
  subjectCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 12,
  },
  subjectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  subjectAvatar: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  subjectAvatarText: {
    color: COLORS.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  subjectName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  ratingBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 10,
    marginRight: 8,
  },
  ratingBadgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  starRow: {
    flexDirection: 'row',
  },
  starBtn: {
    paddingHorizontal: 2,
  },
  ratingHelp: {
    paddingHorizontal: 14,
    paddingBottom: 8,
    fontSize: 12,
    color: COLORS.textLight,
  },
  weakChaptersToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  weakChaptersToggleText: {
    fontSize: 13,
    color: COLORS.textMedium,
  },
  chaptersGrid: {
    paddingHorizontal: 10,
    paddingTop: 4,
    paddingBottom: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  chapterCell: {
    width: '50%',
    paddingHorizontal: 4,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chapterCheckbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  chapterCheckboxChecked: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  chapterLabel: {
    flex: 1,
    fontSize: 12,
    color: COLORS.textDark,
  },
  chaptersEmpty: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 12,
    color: COLORS.textLight,
  },

  // Daily hours slider
  sliderBlock: {
    marginTop: 8,
    marginBottom: 8,
  },
  sliderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sliderLabel: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textDark,
  },
  sliderValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.primary,
  },
  sliderTrack: {
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.border,
    position: 'relative',
    marginVertical: 14,
  },
  sliderFill: {
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  sliderThumb: {
    position: 'absolute',
    top: -7,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#555',
    marginLeft: -10,
  },
  sliderTicksRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  sliderTick: {
    fontSize: 11,
    color: COLORS.textLight,
  },

  // ============== Diagnostic step ==============
  diagnosticCard: {
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
  },
  diagnosticHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  diagnosticIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  diagnosticTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 6,
  },
  diagnosticDesc: {
    fontSize: 12,
    color: 'rgba(255,255,255,0.85)',
    lineHeight: 17,
  },
  diagnosticHighlight: {
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  diagnosticHighlightIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  diagnosticHighlightTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 2,
  },
  diagnosticHighlightDesc: {
    fontSize: 11,
    color: 'rgba(255,255,255,0.85)',
  },
  whatYouGetTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textDark,
    marginBottom: 10,
  },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  bulletDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primaryLight,
    marginRight: 10,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bulletText: {
    flex: 1,
    fontSize: 13,
    color: COLORS.textDark,
  },
  infoBox: {
    backgroundColor: COLORS.primaryLight,
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 16,
  },
  infoBoxIcon: {
    marginRight: 8,
    marginTop: 1,
  },
  infoBoxText: {
    flex: 1,
    fontSize: 12,
    color: COLORS.primary,
    lineHeight: 17,
  },
  warningBox: {
    backgroundColor: '#FEF9C3',
    borderRadius: 12,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 12,
  },
  warningBoxText: {
    flex: 1,
    fontSize: 12,
    color: '#92400E',
    lineHeight: 17,
  },

  // ============== Complete step ==============
  completeContainer: {
    flex: 1,
    backgroundColor: '#1A1150',
  },
  completeContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCircleOuter: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: 'rgba(34, 197, 94, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  successCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: COLORS.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  completeTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: 8,
  },
  completeSubtitle: {
    fontSize: 14,
    color: '#A89FD6',
    textAlign: 'center',
    marginBottom: 28,
    lineHeight: 20,
  },
  summaryCard: {
    width: '100%',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: 18,
    marginBottom: 24,
  },
  summaryHeading: {
    fontSize: 11,
    fontWeight: '700',
    color: '#A89FD6',
    letterSpacing: 1,
    marginBottom: 14,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  summaryRowLast: {
    marginBottom: 0,
  },
  summaryIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  summaryLabel: {
    fontSize: 11,
    color: '#A89FD6',
    marginBottom: 2,
  },
  summaryValue: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.white,
  },
  goDashboardBtn: {
    width: '100%',
    backgroundColor: COLORS.white,
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 12,
  },
  goDashboardText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1A1150',
  },
  exploreBtn: {
    width: '100%',
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
  },
  exploreBtnText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.white,
  },
});
