import { StyleSheet } from 'react-native';

const PRIMARY = '#4F46E5';
const NAVY = '#12102B';
const LAVENDER_BG = '#F5F4FF';
const TEXT_DARK = '#0F0E2C';
const TEXT_GRAY = '#6B7280';
const BORDER = '#E9E7FF';
const GREEN = '#16A34A';

export const homeStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#FFFFFF' },

  /* ── Header ── */
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF0F5',
    backgroundColor: '#FFFFFF',
  },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  logoIcon: {
    width: 30,
    height: 30,
    backgroundColor: PRIMARY,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoIconText: { color: '#FFFFFF', fontSize: 15 },
  logoText: { fontSize: 18, fontWeight: '700', color: TEXT_DARK },
  headerRight: { flexDirection: 'row', alignItems: 'center', gap: 10, flexShrink: 0 },
  // Compact override for the country chip — the landing header carries four
  // elements, so it can't afford the picker's default padding.
  headerCountryChip: { paddingHorizontal: 8, paddingVertical: 6, gap: 4 },
  loginText: { fontSize: 12, color: '#374151', fontWeight: '500' },
  signupBtn: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  signupText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' },

  /* ── Hero ── */
  heroSection: { paddingHorizontal: 20, paddingTop: 28, paddingBottom: 32, backgroundColor: '#FFFFFF' },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: LAVENDER_BG,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
    marginBottom: 16,
  },
  badgeText: { color: PRIMARY, fontSize: 12, fontWeight: '600' },
  heroTitle: { fontSize: 28, fontWeight: '800', color: TEXT_DARK, lineHeight: 34, marginBottom: 14 },
  heroDescription: { fontSize: 15, color: TEXT_GRAY, lineHeight: 23, marginBottom: 22 },
  primaryBtn: {
    backgroundColor: PRIMARY,
    paddingVertical: 15,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  primaryBtnText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },
  outlineBtn: {
    borderWidth: 1.5,
    borderColor: BORDER,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: 22,
  },
  outlineBtnText: { color: TEXT_DARK, fontSize: 15, fontWeight: '600' },

  /* Hero stats row */
  heroStatsRow: { flexDirection: 'row', marginBottom: 26 },
  heroStatItem: { flex: 1, alignItems: 'center' },
  heroStatDivider: { width: 1, backgroundColor: '#E5E7EB', marginHorizontal: 4 },
  heroStatValue: { fontSize: 20, fontWeight: '800', color: PRIMARY, marginBottom: 2 },
  heroStatLabel: { fontSize: 11, color: TEXT_GRAY },

  /* Readiness card */
  readinessCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 18,
    borderWidth: 1,
    borderColor: '#F0EDFF',
    shadowColor: PRIMARY,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 4,
  },
  // Shown when the CMS has no home page for the selected country.
  noContentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: '#EEF0F5',
    alignItems: 'center',
    marginBottom: 22,
  },
  noContentTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: TEXT_DARK,
    textAlign: 'center',
    marginBottom: 6,
  },
  noContentText: {
    fontSize: 14,
    lineHeight: 21,
    color: '#6B7280',
    textAlign: 'center',
  },
  readinessPillsRow: { flexDirection: 'row', gap: 8, marginBottom: 18, flexWrap: 'wrap' },
  readinessPill: {
    backgroundColor: LAVENDER_BG,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 14,
  },
  readinessPillText: { fontSize: 11, fontWeight: '700', color: PRIMARY },
  readinessTopRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 20 },
  readinessRing: {
    width: 78,
    height: 78,
    borderRadius: 39,
    backgroundColor: LAVENDER_BG,
    borderWidth: 5,
    borderColor: '#F59E0B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  readinessRingText: { fontSize: 20, fontWeight: '800', color: TEXT_DARK },
  readinessLabel: { fontSize: 11, fontWeight: '700', color: TEXT_GRAY, letterSpacing: 0.5, marginBottom: 3 },
  readinessStatus: { fontSize: 16, fontWeight: '700', color: TEXT_DARK, marginBottom: 3 },
  readinessSub: { fontSize: 12, color: TEXT_GRAY },
  subjectRow: { marginBottom: 12 },
  subjectHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 6 },
  subjectNameRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  subjectName: { fontSize: 13, fontWeight: '600', color: TEXT_DARK },
  subjectPercent: { fontSize: 13, fontWeight: '700' },
  subjectTrack: { height: 6, borderRadius: 3, backgroundColor: '#F0F0F5', overflow: 'hidden' },
  subjectFill: { height: 6, borderRadius: 3 },

  /* ── Popular courses ── */
  sectionWrap: { paddingHorizontal: 20, paddingVertical: 32, backgroundColor: '#FFFFFF' },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  sectionTitleLeft: { fontSize: 20, fontWeight: '800', color: TEXT_DARK },
  sectionViewAll: { fontSize: 13, fontWeight: '600', color: PRIMARY },
  courseGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  courseCard: {
    width: '48%',
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#EFEEF5',
  },
  courseCardTopRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  courseIconBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: LAVENDER_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  courseIcon: { fontSize: 18 },
  courseTag: {
    backgroundColor: '#ECFDF5',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    alignSelf: 'flex-start',
    height: 20,
  },
  courseTagText: { fontSize: 10, fontWeight: '700', color: GREEN },
  courseTitle: { fontSize: 15, fontWeight: '700', color: TEXT_DARK, marginBottom: 4 },
  courseDesc: { fontSize: 12, color: TEXT_GRAY, lineHeight: 17, marginBottom: 12, minHeight: 34 },
  courseMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  courseMetaText: { fontSize: 11, color: TEXT_GRAY },
  coursePriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, borderTopWidth: 1, borderTopColor: '#F1F0F7', paddingTop: 10 },
  courseOldPrice: { fontSize: 12, color: '#B0AEC0', textDecorationLine: 'line-through' },
  courseFreeText: { fontSize: 13, fontWeight: '700', color: GREEN },

  /* ── Popular courses, CMS exams — one full-width card per row ── */
  examCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: BORDER,
  },
  examCardTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  examFeaturedPill: {
    backgroundColor: LAVENDER_BG,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
  },
  examFeaturedText: { fontSize: 11.5, fontWeight: '700', color: PRIMARY },
  examCardTitle: { fontSize: 16, fontWeight: '800', color: TEXT_DARK },
  examCardSubjects: { fontSize: 12.5, color: TEXT_GRAY, lineHeight: 18, marginTop: 4 },
  examCardDivider: { height: 1, backgroundColor: '#F1F0F7', marginVertical: 12 },
  examCardFooter: { flexDirection: 'row', alignItems: 'center', gap: 14 },
  examCardMeta: { fontSize: 12, color: TEXT_GRAY, fontWeight: '600' },
  examCardFree: { fontSize: 13, fontWeight: '800', color: GREEN, marginLeft: 'auto' },

  /* ── Featured exam (CMS) — rendered inside the hero's card slot ── */
  featuredName: { fontSize: 17, fontWeight: '800', color: TEXT_DARK, marginTop: 4 },
  featuredDesc: { fontSize: 13, color: TEXT_GRAY, lineHeight: 19, marginTop: 6 },
  featuredMetaRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  featuredMetaChip: {
    backgroundColor: LAVENDER_BG,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
  },
  featuredMetaText: { fontSize: 11.5, fontWeight: '600', color: PRIMARY },
  featuredSubjectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#F1F0F7',
    paddingTop: 10,
    marginTop: 10,
  },
  featuredSubjectName: { fontSize: 13.5, fontWeight: '700', color: TEXT_DARK, flexShrink: 1 },
  featuredSubjectMeta: { fontSize: 11.5, color: TEXT_GRAY },

  /* ── How it works ── */
  howGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  howCard: {
    width: '48%',
    backgroundColor: LAVENDER_BG,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
  },
  howIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  howIcon: { fontSize: 18 },
  howBadge: {
    position: 'absolute',
    top: -6,
    right: -6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: PRIMARY,
    justifyContent: 'center',
    alignItems: 'center',
  },
  howBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700' },
  howTitle: { fontSize: 14, fontWeight: '700', color: TEXT_DARK, marginBottom: 6 },
  howDesc: { fontSize: 12, color: TEXT_GRAY, lineHeight: 17 },

  /* ── Leveling card + testimonial ── */
  levelingCard: {
    backgroundColor: PRIMARY,
    borderRadius: 16,
    padding: 22,
    marginBottom: 16,
  },
  levelingTitle: { fontSize: 19, fontWeight: '800', color: '#FFFFFF', lineHeight: 25, marginBottom: 10 },
  levelingDesc: { fontSize: 13, color: 'rgba(255,255,255,0.85)', lineHeight: 20, marginBottom: 16 },
  levelingPillsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  levelingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 14,
  },
  levelingPillText: { color: '#FFFFFF', fontSize: 12, fontWeight: '600' },

  testimonialCard: {
    backgroundColor: '#F9FAFB',
    borderRadius: 16,
    padding: 22,
    borderWidth: 1,
    borderColor: '#F0EDFF',
  },
  testimonialStars: { color: '#F5C842', fontSize: 15, marginBottom: 12, letterSpacing: 2 },
  testimonialQuote: { fontSize: 14, color: TEXT_DARK, lineHeight: 22, marginBottom: 16 },
  testimonialAuthorRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  testimonialAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: LAVENDER_BG,
    justifyContent: 'center',
    alignItems: 'center',
  },
  testimonialAvatarText: { color: PRIMARY, fontSize: 13, fontWeight: '700' },
  testimonialName: { fontSize: 14, fontWeight: '700', color: TEXT_DARK },
  testimonialSub: { fontSize: 12, color: TEXT_GRAY, marginTop: 1 },

  /* ── CTA ── */
  ctaSection: { backgroundColor: '#ffffff', paddingHorizontal: 24, paddingVertical: 48, alignItems: 'center', },
  ctaTitle: { fontSize: 26, fontWeight: '800', color: '#000000', textAlign: 'center', marginBottom: 12 },
  ctaSubtitle: { fontSize: 14, color: 'rgba(0,0,0,0.65)', textAlign: 'center', marginBottom: 26, lineHeight: 21 },
  ctaButton: {
    backgroundColor: PRIMARY,
    paddingVertical: 15,
    paddingHorizontal: 32,
    borderRadius: 12,
    width: '100%',
    alignItems: 'center',
  },
  ctaButtonText: { color: '#FFFFFF', fontSize: 15, fontWeight: '700' },

  /* ── Footer ── */
  footer: { backgroundColor: NAVY, paddingHorizontal: 20, paddingTop: 36, paddingBottom: 24 },
  footerLogoRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 10 },
  footerLogoIcon: {
    width: 28,
    height: 28,
    backgroundColor: PRIMARY,
    borderRadius: 7,
    justifyContent: 'center',
    alignItems: 'center',
  },
  footerLogoIconText: { color: '#FFFFFF', fontSize: 13 },
  footerLogoText: { fontSize: 18, fontWeight: '700', color: '#FFFFFF' },
  footerDescription: { fontSize: 12, color: '#9CA3AF', marginBottom: 26, lineHeight: 18 },
  footerColumnsRow: { flexDirection: 'row', marginBottom: 26, gap: 20 },
  footerColumn: { flex: 1 },
  footerHeading: { fontSize: 13, fontWeight: '700', color: '#FFFFFF', marginBottom: 10 },
  footerLink: { fontSize: 12, color: '#9CA3AF', marginBottom: 8 },
  copyright: {
    fontSize: 11,
    color: '#6B7280',
    textAlign: 'center',
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
  },
});