import { StyleSheet } from 'react-native';
import { COLORS } from '@/src/styles/styles';

export const profileStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.white },
  scroll: { flex: 1, backgroundColor: COLORS.background },
  scrollContent: { paddingBottom: 16 },
  body: { flex: 1, backgroundColor: COLORS.background, paddingTop: 6 },

  backButton: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 16,
  paddingVertical: 14,
  marginLeft: 10,
  backgroundColor: COLORS.white,

},

backText: {
  fontSize: 24,
  alignItems: 'flex-start',
  fontWeight: '700',
  color: COLORS.textDark,
  marginLeft: 16,
},

  // ── Hero ──
  heroCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginTop: 4,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 16,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },
  heroAvatar: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroAvatarText: { color: COLORS.white, fontSize: 20, fontWeight: '800' },
  heroInfo: { flex: 1, alignItems: 'flex-start' },
  heroName: { fontSize: 17, fontWeight: '800', color: COLORS.textDark, marginBottom: 2 },
  heroEmail: { fontSize: 13, color: COLORS.textLight, marginBottom: 8 },
  heroBadgeChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  heroBadgeText: { fontSize: 10, color: COLORS.primary, fontWeight: '700', letterSpacing: 0.5 },

  // ── Card ──
  card: {
    backgroundColor: COLORS.white,
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 16,
    padding: 18,
    shadowColor: COLORS.cardShadow,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 2,
  },

  // ── Section header ──
  sectionHeader: { marginBottom: 14 },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: COLORS.textDark },
  sectionSubtitle: { fontSize: 12, color: COLORS.textLight, marginTop: 3 },

  // ── Inputs ──
  inputGroup: { marginBottom: 12 },
  inputLabel: { fontSize: 12, fontWeight: '600', color: COLORS.textMedium, marginBottom: 6 },
  inputWrap: { position: 'relative' },
  inputIcon: {
    position: 'absolute',
    left: 10,
    top: 12,
    zIndex: 1,
  },
  textInput: {
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: COLORS.textDark,
  },
  addExamInlineRow: {
  flexDirection: 'row',
  gap: 10,
  marginTop: 8,
},
addExamInlineField: {
  flex: 1,
},

  // ── Save button ──
  saveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    paddingVertical: 13,
    marginTop: 6,
  },
  saveBtnText: { color: COLORS.white, fontWeight: '700', fontSize: 14 },

  // ── Exam list rows ──
  examRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 14,
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 8,
  },
  examRowInfo: { flex: 1 },
  examRowName: { fontSize: 14, fontWeight: '600', color: COLORS.textDark },
  examRowYear: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  examRowDelete: {
    width: 34,
    height: 34,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.redLight,
    marginLeft: 10,
  },

  // ── Add exam form ──
  addExamForm: { marginTop: 8 },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  dropdownText: { fontSize: 14, color: COLORS.textDark },
  dropdownOptions: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginTop: 4,
    overflow: 'hidden',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  dropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  dropdownOptionText: { fontSize: 14, color: COLORS.textDark },
  dropdownOptionAssigned: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    overflow: 'hidden',
  },

  addExamBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    paddingVertical: 13,
    marginTop: 16,
  },
  addExamBtnText: { color: COLORS.white, fontWeight: '700', fontSize: 14 },

  // ── Security ──
  securityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 14,
    backgroundColor: COLORS.inputBg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  securityIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  securityInfo: { flex: 1 },
  securityTitle: { fontSize: 14, fontWeight: '600', color: COLORS.textDark },
  securitySub: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },

  // ── Notifications ──
  notifRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    gap: 12,
  },
  notifRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  notifInfo: { flex: 1 },
  notifLabel: { fontSize: 13, fontWeight: '600', color: COLORS.textDark, lineHeight: 18 },
  notifChannel: { fontSize: 11, color: COLORS.textLight, marginTop: 3 },

  // ── Danger Zone ──
  dangerCard: {
    marginHorizontal: 16,
    marginTop: 14,
    borderRadius: 16,
    padding: 18,
    backgroundColor: COLORS.redLight,
    borderWidth: 1,
    borderColor: COLORS.redBorder,
  },
  dangerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  dangerTitle: { fontSize: 15, fontWeight: '700', color: COLORS.red },
  dangerDesc: { fontSize: 13, color: COLORS.textMedium, lineHeight: 20, marginBottom: 16 },
  deleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1.5,
    borderColor: COLORS.red,
    borderRadius: 10,
    paddingVertical: 11,
    backgroundColor: COLORS.white,
  },
  deleteBtnText: { color: COLORS.red, fontWeight: '700', fontSize: 14 },

  // ── Change Password form ──
  pwdForm: {
    marginTop: 14,
    paddingTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F8',
  },
  pwdInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F7F8FC',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E8E8F0',
    paddingRight: 10,
    overflow: 'hidden',
  },
  pwdInput: {
    flex: 1,
    paddingHorizontal: 14,
    paddingVertical: 11,
    fontSize: 14,
    color: '#1A1A2E',
  },
  eyeBtn: {
    padding: 6,
  },
  pwdError: {
    marginTop: 10,
    fontSize: 12,
    color: '#EF4444',
    fontWeight: '600',
  },
  pwdActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 16,
  },
  updatePwdBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#6C63FF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    flex: 1,
    justifyContent: 'center',
  },
  updatePwdBtnText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 17,
  },
  cancelPwdBtn: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#E8E8F0',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelPwdBtnText: {
    color: '#4A4A6A',
    fontWeight: '600',
    fontSize: 13,
  },

  // ── Change Password modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26, 26, 46, 0.45)',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  modalCard: {
    backgroundColor: COLORS.white,
    borderRadius: 20,
    paddingTop: 18,
    paddingBottom: 8,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
    elevation: 8,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingHorizontal: 18,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  modalTitleWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  modalTitle: { fontSize: 16, fontWeight: '800', color: COLORS.textDark },
  modalSubtitle: { fontSize: 12, color: COLORS.textLight, marginTop: 2 },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.background,
  },
  modalBody: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 10,
  },
});
