import { StyleSheet } from "react-native";

export const tutorModalStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#EEEFF5" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: "#fff",
    borderBottomWidth: 1,
    borderBottomColor: "#EAEAF0",
  },
  headerTitleRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  headerTitle: { fontSize: 16, fontWeight: "800", color: "#1A1A2E" },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#F1F2F6",
    alignItems: "center",
    justifyContent: "center",
  },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, gap: 10 },
  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    marginBottom: 6,
  },
  questionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#AAAAAA",
    letterSpacing: 1,
    marginBottom: 6,
  },
  questionText: { fontSize: 14, color: "#1A1A2E", lineHeight: 20 },
  initRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 16,
  },
  emptyState: { paddingVertical: 12, gap: 12 },
  emptyText: { fontSize: 13, color: "#9CA3AF", textAlign: "center" },
  quickWrap: { gap: 8 },
  quickChip: {
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  quickChipText: { fontSize: 13, color: '#6C63FF', fontWeight: "600" },
  bubble: {
    maxWidth: "85%",
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 14,
  },
  bubbleUser: {
    alignSelf: "flex-end",
    backgroundColor: "#6C63FF",
    borderBottomRightRadius: 4,
  },
  bubbleTutor: {
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderBottomLeftRadius: 4,
  },
  bubbleUserText: { fontSize: 14, color: "#fff", lineHeight: 20 },
  bubbleTutorText: { fontSize: 14, color: "#1A1A2E", lineHeight: 20 },
  sourcesBox: {
    marginTop: 10,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F1F2F6",
    gap: 4,
  },
  sourcesLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#AAAAAA",
    letterSpacing: 1,
    marginBottom: 2,
  },
  sourceRow: { flexDirection: "row", alignItems: "center", gap: 5 },
  sourceText: { fontSize: 11, color: "#6B7280", flex: 1 },
  notGroundedNote: {
    marginTop: 8,
    fontSize: 11,
    fontStyle: "italic",
    color: "#B45309",
  },
  composer: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#EAEAF0",
  },
  input: {
    flex: 1,
    maxHeight: 120,
    minHeight: 40,
    backgroundColor: "#F1F2F6",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 14,
    color: "#1A1A2E",
  },
  sendBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#6C63FF",
    alignItems: "center",
    justifyContent: "center",
  },
  sendBtnDisabled: { backgroundColor: "#BFD3F5" },
});
