import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../styles";

export const qStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: COLORS.background },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 32 },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    gap: 10,
  },
  headerLeft: { minWidth: 70 },
  practiceMode: { fontSize: 10, color: COLORS.textLight, fontWeight: '600', letterSpacing: 0.5 },
  chapterLabel: { fontSize: 13, fontWeight: '700', color: COLORS.textDark },
  headerCenter: { flex: 1, gap: 4 },
  progressText: { fontSize: 11, color: COLORS.textLight, textAlign: 'center' },
  endBtn: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: COLORS.red,
  },
  endBtnText: { fontSize: 12, fontWeight: '700', color: COLORS.white },

  metaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 16,
  },
  qNumBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  qNumText: { fontSize: 12, fontWeight: '600', color: COLORS.textMedium },
  typeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: COLORS.primaryLight,
    borderRadius: 8,
  },
  typeText: { fontSize: 12, fontWeight: '600', color: COLORS.primary },
  marksBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  marksGreen: { fontSize: 12, fontWeight: '700', color: COLORS.green },
  marksRed: { fontSize: 12, fontWeight: '700', color: COLORS.red },
  timerChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: COLORS.primaryLight,
  },
  timerChipText: { fontSize: 12, fontWeight: '700', color: COLORS.primary },

  questionText: {
    fontSize: 15,
    color: COLORS.textDark,
    lineHeight: 24,
    fontWeight: '500',
    marginBottom: 20,
  },

  optionsList: { gap: 10 },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
  },
  optionSelected: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  optionCorrect: {
    borderColor: COLORS.green,
    backgroundColor: COLORS.greenLight,
  },
  optionWrong: {
    borderColor: COLORS.red,
    backgroundColor: COLORS.redLight,
  },
  optionDimmed: {
    opacity: 0.5,
  },
  optionBubble: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
  },
  optionBubbleSelected: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  optionBubbleCorrect: {
    backgroundColor: COLORS.green,
    borderColor: COLORS.green,
  },
  optionBubbleWrong: {
    backgroundColor: COLORS.red,
    borderColor: COLORS.red,
  },
  optionBubbleText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMedium,
  },
  optionText: {
    flex: 1,
    fontSize: 14,
    color: COLORS.textDark,
    fontWeight: '500',
  },
  optionTextSelected: { color: COLORS.primary, fontWeight: '600' },
  optionTextCorrect: { color: COLORS.green, fontWeight: '600' },
  optionTextWrong: { color: COLORS.red, fontWeight: '600' },
  optionTextDimmed: { color: COLORS.textLight },

  feedbackBox: {
    marginTop: 20,
    borderRadius: 14,
    padding: 16,
    borderWidth: 1.5,
  },
  feedbackCorrect: {
    backgroundColor: COLORS.greenLight,
    borderColor: COLORS.green,
  },
  feedbackWrong: {
    backgroundColor: COLORS.redLight,
    borderColor: COLORS.red,
  },
  feedbackHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  feedbackTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  answerRow: { gap: 4, marginBottom: 12 },
  yourAnswer: { fontSize: 13, color: COLORS.textMedium },
  correctAnswer: { fontSize: 13, color: COLORS.textMedium },
  explanationBox: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 10,
    padding: 12,
    gap: 6,
  },
  explanationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  explanationTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.orange,
  },
  explanationText: {
    fontSize: 13,
    color: COLORS.textMedium,
    lineHeight: 20,
  },
  explanationStepHeading: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.primary,
    marginBottom: 2,
  },

  bottomBar: {
    backgroundColor: COLORS.white,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: Platform.OS === 'ios' ? 8 : 14,
    gap: 10,
  },
  bottomActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reviewBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
  },
  reviewBtnActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primaryLight,
  },
  reviewText: { fontSize: 13, fontWeight: '600', color: COLORS.textLight },
  reviewTextActive: { color: COLORS.primary },
  clearBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.redLight,
    backgroundColor: COLORS.redLight,
  },
  clearText: { fontSize: 13, fontWeight: '600', color: COLORS.red },
  answeredBadge: {
    fontSize: 13,
    fontWeight: '600',
    color: COLORS.green,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: COLORS.greenLight,
    borderRadius: 8,
  },
  notVisitedText: {
    fontSize: 13,
    color: COLORS.textLight,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  navBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  navBtnDisabled: { opacity: 0.4 },
  navBtnText: { fontSize: 14, fontWeight: '600', color: COLORS.textMedium },
  saveNextBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.primary,
    borderRadius: 12,
    paddingVertical: 12,
  },
  saveNextBtnDisabled: {
    backgroundColor: COLORS.border,
  },
  saveNextText: { fontSize: 14, fontWeight: '700', color: COLORS.white },
  nextQuestionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.green,
    borderRadius: 12,
    paddingVertical: 12,
  },
  nextQuestionText: { fontSize: 14, fontWeight: '700', color: COLORS.white },
});