// src/json/AssessmentsJson.ts

export function assessmentsdata() {
  return [
    {
      id: 25,
      name: 'Mains 2026',
      description: '',
      exam: { id: 7, name: 'EAMCET' },
      question_count: 30,
      total_duration_minutes: 60,
      student_status: 'live',
      window_label: 'Window closes in Now',
      joined_label: '0/0 joined',
      date_label: 'Started 13 Apr 2026, 4:38 pm',
    },
    {
      id: 28,
      name: 'Eamcet',
      description: '',
      exam: { id: 7, name: 'EAMCET' },
      question_count: 23,
      total_duration_minutes: 60,
      student_status: 'upcoming',
      window_label: 'Starts in Now',
      registered_count: 0,
      date_label: '11 Apr 2026, 5:42 pm',
    },
    {
      id: 29,
      name: 'JEE',
      description: '',
      exam: { id: 3, name: 'JEE' },
      question_count: 10,
      total_duration_minutes: 16,
      student_status: 'upcoming',
      window_label: 'Starts in Now',
      registered_count: 0,
      date_label: '1 Apr 2026, 6:30 pm',
    },
    {
      id: 30,
      name: 'jee',
      description: '',
      exam: { id: 3, name: 'JEE' },
      question_count: 10,
      total_duration_minutes: 16,
      student_status: 'upcoming',
      window_label: 'Starts in Now',
      registered_count: 0,
      date_label: '1 Apr 2026, 6:30 pm',
    },
    {
      id: 21,
      name: 'EAMCET 2028',
      description: 'Eamcet Exam',
      exam: { id: 7, name: 'EAMCET' },
      question_count: 20,
      total_duration_minutes: 10,
      student_status: 'completed',
      date_label: '',
    },
    {
      id: 22,
      name: 'jee',
      description: 'karim',
      exam: { id: 3, name: 'JEE' },
      question_count: 10,
      total_duration_minutes: 3,
      student_status: 'completed',
      date_label: '',
    },
    {
      id: 23,
      name: 'jee',
      description: 'karim',
      exam: { id: 3, name: 'JEE' },
      question_count: 10,
      total_duration_minutes: 2,
      student_status: 'completed',
      date_label: '',
    },
    {
      id: 24,
      name: 'jee',
      description: 'karim',
      exam: { id: 3, name: 'JEE' },
      question_count: 10,
      total_duration_minutes: 2,
      student_status: 'completed',
      date_label: '',
    },
  ];
}