export const mockDataJson = [
  {id: '1',
    exam: 'EAMCET',
    title: 'EAMCET — Custom Mock',
    subject: 'Mathematics',
    duration: '1 hrs',
    questions: 1,
    marks: 1,
    difficulty: 'Medium',
    status: 'in_progress',
    lastAttempt: '9 Apr 2028',
  },
  {id: '2',
    exam: 'EAMCET',
    title: 'EAMCET — Custom Mock',
    subject: 'Mathematics',
    duration: '1 hrs',
    questions: 1,
    marks: 1,
    difficulty: 'Easy',
    status: 'completed',
    score: '1/1',
    percentile: '0%ile',
    accuracy: '0%',
    lastAttempt: '9 Apr 2028, 2:22 pm',
  },
  {id: '3',
    exam: 'EAMCET',
    title: 'EAMCET — Custom Mock',
    subject: 'Physics',
    duration: '1 hrs',
    questions: 1,
    difficulty: 'Hard',
    status: 'not_attempted',
  },
  {id: '4',
    exam: 'EAMCET',
    title: 'EAMCET — Custom Mock',
    subject: 'Mathematics',
    duration: '1 hrs',
    questions: 1,
    difficulty: 'Medium',
    status: 'not_attempted',
  },
  {id: '5',
    exam: 'JEE2',
    title: 'JEE2 — Custom Mock',
    subject: 'Chemistry',
    duration: '1 hr',
    questions: 4,
    difficulty: 'Easy',
    status: 'not_attempted',
  },
  {id: '6',
    exam: 'JEE2',
    title: 'JEE2 — Custom Mock',
    subject: 'Mathematics',
    duration: '1 hr',
    questions: 1,
    difficulty: 'Medium',
    status: 'not_attempted',
  },
];

export const SORT_OPTIONS = [
  'Newest First',
  'Oldest First',
  'Easy → Hard',
  'Hard → Easy',
  'Most Popular',
];

export const EXAM_FILTERS = ['EAMCET', 'JEE', 'JEE Mains', 'JEE2', 'Mains'] as const;
export const DIFFICULTY_FILTERS = ['Easy', 'Medium', 'Hard'] as const;