import { Platform, StyleSheet } from "react-native";

export const examScreenStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#0F1117" },
  scroll: { flex: 1, backgroundColor: "#fff" },
  scrollContent: { padding: 20, paddingBottom: 24 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#0F1117",
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 10,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#1E2130",
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: { flex: 1, gap: 2 },
  headerTitle: { fontSize: 14, fontWeight: "700", color: "#fff" },
  headerSub: { fontSize: 11, color: "#9CA3AF" },
  progressBar: { flexDirection: "row", gap: 2, marginTop: 5, height: 2 },
  progressSeg: { flex: 1, height: 2, borderRadius: 1 },
  timerChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#1E2130",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
  },
  timerChipRed: { backgroundColor: "#2D0A0A" },
  timerText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#E5E7EB",
    fontVariant: ["tabular-nums"] as any,
  },
  menuBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "#1E2130",
    alignItems: "center",
    justifyContent: "center",
  },

  // Tab switch warning
  tabWarningBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  tabWarningText: { flex: 1, fontSize: 12, color: "#B45309", fontWeight: "500" },

  // Q meta
  qMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  qLabel: { fontSize: 11, fontWeight: "700", color: "#9CA3AF", letterSpacing: 1 },
  marksRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  marksChip: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
  marksChipPositive: { backgroundColor: "#ECFDF5", borderColor: "#A7F3D0" },
  marksChipNegative: { backgroundColor: "#FEF2F2", borderColor: "#FECACA" },
  marksChipText: { fontSize: 12, fontWeight: "700", fontVariant: ["tabular-nums"] as any },
  marksChipTextPositive: { color: "#059669" },
  marksChipTextNegative: { color: "#DC2626" },
  markBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
  },
  markBtnActive: { borderColor: "#F59E0B", backgroundColor: "#FEF3C7" },
  markText: { fontSize: 10, fontWeight: "600", color: "#9CA3AF" },
  markTextActive: { color: "#B45309" },

  // Question
  questionText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1A1A2E",
    lineHeight: 24,
    marginBottom: 12,
  },
  questionImage: {
    // A fixed pixel height — NOT a percentage. Inside a ScrollView the content
    // container has no resolved height, so `height: "50%"` blew the image box up
    // to ~half the viewport and left a large empty gap below the diagram.
    width: "100%",
    height: 220,
    resizeMode: "contain",
    borderRadius: 8,
    alignSelf: "center",
    marginBottom: 8,
  },

  // Assertion-Reason
  arCard: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#EEF0F4",
    padding: 14,
    marginBottom: 12,
  },
  arLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#6C5CE7",
    letterSpacing: 0.5,
    marginBottom: 6,
    textTransform: "uppercase",
  },
  arText: { fontSize: 15, color: "#1A1A2E", lineHeight: 22 },

  // Numeric
  selectLabel: { fontSize: 13, fontWeight: "600", color: "#6B7280", marginBottom: 12 },
  numericInput: {
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: "#1A1A2E",
    backgroundColor: "#fff",
  },
  numericInputFilled: { borderColor: '#6C63FF', backgroundColor: "#F0F6FF" },
  numericHint: { fontSize: 12, color: "#9CA3AF", marginTop: 8 },

  // Options
  optionsList: { gap: 10 },
  optRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    padding: 10,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
  },
  optRowSelected: { borderColor: "#6C63FF", backgroundColor: "#F0F6FF" },
  optLetter: {
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  optLetterSelected: { backgroundColor: "#6C63FF", borderColor: "#6C63FF" },
  optLetterText: { fontSize: 13, fontWeight: "700", color: "#6B7280" },
  optLetterTextSelected: { color: "#fff" },
  optText: { fontSize: 15, color: "#1A1A2E", fontWeight: "500" },
  optTextSelected: { color: "#6C63FF", fontWeight: "600" },
  optImage: { width: "100%", height: 120, resizeMode: "contain", marginTop: 8 },

  swipeHint: { textAlign: "center", fontSize: 12, color: "#D1D5DB", marginTop: 20 },

  // Bottom bar
  bottomBar: {
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 8 : 16,
  },
  nextBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#6C63FF",
    borderRadius: 16,
    paddingVertical: 16,
  },
  nextBtnText: { fontSize: 16, fontWeight: "700", color: "#fff" },
  navRow: { flexDirection: "row", gap: 10 },
  prevBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 18,
    paddingVertical: 15,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
  },
  prevBtnText: { fontSize: 14, fontWeight: "700", color: "#555" },
  prevBtnDisabled: { borderColor: "#F0F1F4", backgroundColor: "#fff" },
  submitBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#1A1A2E",
    borderRadius: 16,
    paddingVertical: 15,
  },
  submitBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },

  // Submit sheet
  submitOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  submitSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
  },
  sheetHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#E5E7EB",
    alignSelf: "center",
    marginBottom: 16,
  },
  submitSheetTitle: { fontSize: 20, fontWeight: "800", color: "#1A1A2E", marginBottom: 10 },
  submitSheetDesc: { fontSize: 14, color: "#6B7280", lineHeight: 22, marginBottom: 24 },
  submitSheetBtns: { flexDirection: "row", gap: 12 },
  keepGoingBtn: {
    flex: 1,
    paddingVertical: 15,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  keepGoingText: { fontSize: 15, fontWeight: "700", color: "#1A1A2E" },
  submitNowBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#1A1A2E",
    borderRadius: 14,
    paddingVertical: 15,
  },
  submitNowText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  rightActionsRow: {
  flexDirection: "row",
  alignItems: "center",
  gap: 10,          // <- this is the gap between marks / flag / mark
  marginLeft: "auto",
},

  flagBtn: {
  width: 34,
  height: 34,
  borderRadius: 10,
  borderWidth: 1,
  borderColor: "#E5E7EB",
  alignItems: "center",
  justifyContent: "center",
  backgroundColor: "#fff",
},
});
