import { StyleSheet } from "react-native";

const SCREEN_BG = "#EEEFF5";

export const practiceResultsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: SCREEN_BG },
  topBar: { paddingHorizontal: 16, paddingTop: 12 },
  backBtn: { flexDirection: "row", alignItems: "center", gap: 2, alignSelf: "flex-start" },
  backText: { fontSize: 16, fontWeight: "600", color: '#6C63FF' },

  scroll: { flex: 1 },

  // Results view
  resultsContent: { paddingHorizontal: 20, paddingBottom: 32, alignItems: "center" },
  resultsTitle: { fontSize: 16, fontWeight: "700", color: "#1A1A2E", marginBottom: 18 },
  ringWrap: { marginBottom: 16 },
  ringPct: { fontSize: 32, fontWeight: "800", color: "#1A1A2E" },
  ringSub: { fontSize: 12, color: "#9CA3AF", marginTop: 2 },
  heading: { fontSize: 24, fontWeight: "800", color: "#1A1A2E", marginBottom: 4 },
  subheading: { fontSize: 14, color: "#9CA3AF", marginBottom: 22 },

  statsRow: { flexDirection: "row", gap: 12, alignSelf: "stretch", marginBottom: 14 },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    gap: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  statValue: { fontSize: 20, fontWeight: "800", color: "#1A1A2E", marginTop: 4 },
  statLabel: { fontSize: 12, color: "#9CA3AF" },

  scoreBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    alignSelf: "stretch",
    backgroundColor: "#EAF1FF",
    borderRadius: 14,
    padding: 14,
    marginBottom: 20,
  },
  scoreBannerTitle: { fontSize: 14, fontWeight: "700", color: "#1A1A2E" },
  scoreBannerSub: { fontSize: 12, color: "#6B7280", marginTop: 1 },

  submittingRow: { flexDirection: "row", alignItems: "center", gap: 8, marginBottom: 14 },
  submittingText: { fontSize: 12, color: "#9CA3AF" },

  reviewBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    alignSelf: "stretch",
    backgroundColor: '#6C63FF',
    borderRadius: 14,
    paddingVertical: 16,
    marginBottom: 12,
    shadowColor: "#6C63FF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  reviewBtnText: { fontSize: 16, fontWeight: "700", color: "#fff" },
  doneBtn: {
    alignSelf: "stretch",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingVertical: 15,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 1,
  },
  doneBtnText: { fontSize: 15, fontWeight: "700", color: "#1A1A2E" },
  tryAgain: { marginTop: 14, padding: 6 },
  tryAgainText: { fontSize: 13, fontWeight: "600", color: "#9CA3AF" },

  // ── Review view — matches SolutionViewer (assessments) styling ───────────
  reviewHeader: {
    flexDirection: "column",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: SCREEN_BG,
    paddingLeft: 18,
    gap: 10,
  },
  reviewHeaderTitle: { fontSize: 26, fontWeight: "800", color: "#1A1A2E" },
  reviewScrollContent: { paddingHorizontal: 16, paddingBottom: 40, gap: 16 },

  questionCard: {
    backgroundColor: "#fff",
    borderRadius: 18,
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  qCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  qCardNum: { fontSize: 13, fontWeight: "700", color: "#9CA3AF" },
  outcomeBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
  },
  outcomeBadgeCorrect: { backgroundColor: "#DCFCE7" },
  outcomeBadgeWrong: { backgroundColor: "#FEE2E2" },
  outcomeBadgeText: { fontSize: 12, fontWeight: "700", color: "#6B7280" },
  qCardText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1A1A2E",
    lineHeight: 22,
    marginBottom: 16,
  },
  qCardImage: {
    width: "100%",
    height: 180,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    marginBottom: 16,
  },

  numericAnswerBlock: { marginTop: 2, marginBottom: 6, gap: 6 },
  numericAnswerLine: { fontSize: 15, lineHeight: 22 },
  numericAnswerLabel: { color: "#1A1A2E", fontWeight: "600" },
  numericAnswerValueCorrect: { color: "#22C55E", fontWeight: "800" },
  numericAnswerValueWrong: { color: "#EF4444", fontWeight: "800" },

  optRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
    marginBottom: 8,
  },
  optRowCorrect: { borderColor: "#22C55E", backgroundColor: "#F0FDF4" },
  optRowWrong: { borderColor: "#EF4444", backgroundColor: "#FEF2F2" },
  optLetter: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    textAlign: "center",
    textAlignVertical: "center",
    lineHeight: 28,
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7280",
  },
  optLetterCorrect: { backgroundColor: "#22C55E", borderColor: "#22C55E", color: "#fff" },
  optLetterWrong: { backgroundColor: "#EF4444", borderColor: "#EF4444", color: "#fff" },
  optBody: { flex: 1 },
  optText: { flex: 1, fontSize: 14, color: "#1A1A2E", fontWeight: "500" },
  optImage: {
    width: "100%",
    height: 100,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
    marginTop: 4,
  },
  optTrailing: { flexDirection: "row", alignItems: "center", gap: 6, marginLeft: "auto" },
  youBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: "#EEF0F4",
  },
  youBadgeText: { fontSize: 10, fontWeight: "700", color: "#6B7280", letterSpacing: 0.3 },

  whyBox: {
    marginTop: 10,
    backgroundColor: "#F9FAFB",
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#6C63FF",
    overflow: "hidden",
  },
  whyToggleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  whyToggleLabel: { fontSize: 13, fontWeight: "700", color: "#1A1A2E" },
  whyBody: { paddingHorizontal: 12, paddingBottom: 12 },
  whyText: { fontSize: 13, color: "#6B7280", lineHeight: 20 },
});