import { Platform, StyleSheet } from "react-native";

export const practiceQuestionsProgressBarStyles = StyleSheet.create({
  container: { flexDirection: "row", gap: 3, height: 3, flex: 1 },
  segment: { flex: 1, borderRadius: 2 },
  segmentActive: { flex: 1.4 },
});

export const practiceQuestionsStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFFFF" },
  scroll: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 24 },

  // Header
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    gap: 10,
  },
  closeBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: { flex: 1, gap: 2 },
  headerChapter: { fontSize: 14, fontWeight: "700", color: "#1A1A2E" },
  headerMode: { fontSize: 11, color: "#9CA3AF" },
  tutorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: '#6C63FF',
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
  },
  tutorText: { fontSize: 12, fontWeight: "700", color: "#fff" },

  // Question
  qMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  qLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#AAAAAA",
    letterSpacing: 1,
  },
  marksRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  marksChip: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, borderWidth: 1 },
  marksChipPositive: { backgroundColor: "#ECFDF5", borderColor: "#A7F3D0" },
  marksChipNegative: { backgroundColor: "#FEF2F2", borderColor: "#FECACA" },
  marksChipText: { fontSize: 12, fontWeight: "700", fontVariant: ["tabular-nums"] as any },
  marksChipTextPositive: { color: "#059669" },
  marksChipTextNegative: { color: "#DC2626" },
  qText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A2E",
    lineHeight: 26,
    marginBottom: 20,
  },

  // Images
  qImage: {
    width: "100%",
    height: 200,
    borderRadius: 12,
    backgroundColor: "#F3F4F6",
    marginBottom: 20,
  },
  optImage: {
    width: "100%",
    height: 110,
    borderRadius: 10,
    backgroundColor: "#F3F4F6",
    marginTop: 4,
  },
  optBody: { flex: 1 },

  // Options
  optionsList: { gap: 10 },
  optRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#fff",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
  },
  optSelected: { borderColor: "#6C63FF", backgroundColor: "#F0F6FF" },
  optCorrect: { borderColor: "#22C55E", backgroundColor: "#F0FDF4" },
  optWrong: { borderColor: "#EF4444", backgroundColor: "#FEF2F2" },
  optDimmed: { opacity: 0.45 },
  optLetter: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
    flexShrink: 0,
  },
  optLetterSelected: { backgroundColor: "#6C63FF", borderColor: "#6C63FF" },
  optLetterCorrect: { backgroundColor: "#22C55E", borderColor: "#22C55E" },
  optLetterWrong: { backgroundColor: "#EF4444", borderColor: "#EF4444" },
  optLetterText: { fontSize: 12, fontWeight: "700" },
  optText: { flex: 1, fontSize: 14, fontWeight: "500", color: "#1A1A2E" },

  // Numerical input
  numericLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#6B7280",
    marginBottom: 8,
  },
  numericInput: {
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 16,
    fontSize: 18,
    fontWeight: "700",
    color: "#1A1A2E",
    backgroundColor: "#fff",
  },
  numericCorrect: { borderColor: "#22C55E", backgroundColor: "#F0FDF4" },
  numericWrong: { borderColor: "#EF4444", backgroundColor: "#FEF2F2" },
  numericHint: { fontSize: 12, color: "#9CA3AF", marginTop: 8 },

  // Feedback
  feedbackBox: {
    borderRadius: 16,
    padding: 16,
    borderWidth: 1.5,
    marginTop: 4,
  },
  feedbackCorrect: { backgroundColor: "#F0FDF4", borderColor: "#86EFAC" },
  feedbackWrong: { backgroundColor: "#FEF2F2", borderColor: "#FCA5A5" },
  feedbackHeader: { marginBottom: 10 },
  feedbackTitle: { fontSize: 16, fontWeight: "800" },
  answerInfo: { marginBottom: 10 },
  answerInfoText: { fontSize: 13, color: "#6B7280" },
  explBox: {
    backgroundColor: "rgba(255,255,255,0.75)",
    borderRadius: 12,
    padding: 12,
  },
  explHeader: { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 6 },
  explTitle: { fontSize: 13, fontWeight: "700", color: "#F59E0B" },
  explText: { fontSize: 13, color: "#555", lineHeight: 20 },
  explStepHead: { fontSize: 13, fontWeight: "700", color: "#6C63FF", marginBottom: 2 },
  askTutorBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    marginTop: 12,
    borderWidth: 1.5,
    borderColor: "#6C63FF",
    borderRadius: 20,
    paddingHorizontal: 14,
    paddingVertical: 8,
    alignSelf: "flex-start",
    backgroundColor: "#fff",
  },
  askTutorText: { fontSize: 12, fontWeight: "700", color: "#6C63FF" },

  // Bottom bar
  bottomBar: {
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: Platform.OS === "ios" ? 8 : 16,
  },
  checkBtn: {
    backgroundColor: "#6C63FF",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  checkBtnDisabled: { backgroundColor: "#D1D5DB" },
  checkBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
  // Stretch so Prev and the primary button share the exact same height and
  // their top/bottom edges line up.
  navRow: { flexDirection: "row", gap: 10, alignItems: "stretch" },
  prevBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    paddingHorizontal: 16,
    paddingVertical: 15,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#E5E7EB",
    backgroundColor: "#fff",
  },
  prevBtnText: { fontSize: 14, fontWeight: "700", color: "#555" },
  nextBtn: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingHorizontal: 12,
    backgroundColor: "#22C55E",
    borderRadius: 16,
    paddingVertical: 15,
  },
  nextBtnText: { fontSize: 15, fontWeight: "700", color: "#fff" },
});
