import { StyleSheet } from "react-native";

export const subTopicStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#EEEFF5" },
  scroll: { flex: 1 },
  scrollContent: { paddingBottom: 32 },
  topBar: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 0,
    backgroundColor: "#EEEFF5",
  },
  backBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    alignSelf: "flex-start",
  },
  backText: {
    fontSize: 15,
    fontWeight: "600",
    color: "#3B7DF8",
  },
  pageTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#1A1A2E",
    paddingHorizontal: 20,
    paddingTop: 6,
    paddingBottom: 16,
    backgroundColor: "#EEEFF5",
  },
  banner: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    marginHorizontal: 16,
    marginBottom: 20,
    padding: 18,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  bannerStatus: {
    fontSize: 17,
    fontWeight: "800",
    color: "#1A1A2E",
  },
  bannerMeta: {
    fontSize: 13,
    color: "#9CA3AF",
    marginTop: 3,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#AAAAAA",
    letterSpacing: 1,
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  topicWrap: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    marginHorizontal: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  topicRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
    gap: 12,
  },
  topicRowLast: {
    borderBottomWidth: 0,
  },
  topicInfo: { flex: 1 },
  topicName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1A1A2E",
  },
  topicMeta: {
    fontSize: 12,
    color: "#9CA3AF",
    marginTop: 2,
  },
  topicDot: {
    width: 32,
    height: 32,
    borderRadius: 9,
  },
  loadingWrap: {
    alignItems: "center",
    paddingVertical: 60,
    gap: 12,
  },
  loadingText: { fontSize: 14, color: "#9CA3AF" },
});
